# Домашнее задание. Линейная алгебра и библиотека NumPy
В этом домашнем задании вам предстоит самостоятельно реализовать линейно-алгебраические операции с помощью чистого Python, а затем попрактиковаться в использовании уже готовых реализаций из numpy. Кроме того, вы сравните время работы вашей реализации с реализацией из библиотеки NumPy и убедитесь, что скорость работы "коробочных" реализаций выше.

In [38]:
import numpy as np
import random
import scipy.stats as sps

## Задание 1
Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

<class 'numpy.ndarray'> [0.25517625 0.34595235 0.36132484]


In [ ]:
def scalar_product(a, b):
    """  
    a: np.array[, n] --- первая матрица-аргумент длиной n
    b: np.array[, n] --- вторая матрица-аргумент длиной n
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, не используя функции из пакета numpy

    """ 
    pass

In [ ]:
def np_scalar_product(a,b):
    """  
    a: np.array[, n] --- первая матрица-аргумент
    b: np.array[, n] --- вторая матрица-аргумент
    return c: float  --- результат скалярного произведения векторов a и b

    Функция принимает на вход два вектора длиной n
    Возвращает число, равное их скалярному произведению a x b = c 

    Реализуйте скалярное умножение векторов, используя функции из пакета numpy
    """ 
    pass

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)

# проверим корректность:
assert np.allclose(product_1, product_2)

## Задание 2
Вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета `numpy` и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))

# Выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?

# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.395839   0.21379428 0.07247983 ... 0.64980615 0.64291476 0.32526086]
 [0.99447693 0.63253878 0.10648252 ... 0.09038331 0.08219018 0.63331995]
 [0.03470463 0.83264811 0.00266264 ... 0.41459466 0.20456353 0.88582864]
 ...
 [0.6902504  0.10926463 0.64770747 ... 0.7091193  0.19629277 0.9975028 ]
 [0.64204202 0.65320852 0.35489944 ... 0.00704072 0.78367391 0.59237454]
 [0.84137914 0.89991396 0.55261748 ... 0.3186097  0.48761123 0.91937383]]
[[0.19223844 0.02409304 0.41697875 ... 0.2896223  0.03328157 0.64914984]
 [0.59910385 0.40862453 0.40050159 ... 0.89650084 0.46264964 0.90442002]
 [0.87800265 0.28263125 0.82332552 ... 0.71561631 0.51356527 0.58747008]
 ...
 [0.83887046 0.24098338 0.29652699 ... 0.75683419 0.17818834 0.37654114]
 [0.26376756 0.33976523 0.95381248 ... 0.8179511  0.18956817 0.70542156]
 [0.02341907 0.56668502 0.53320765 ... 0.52531754 0.27821011 0.91949749]]


In [ ]:
def mult(a, b):
    """  
    a: list of "size" lists, each contains "size" floats --- первая матрица-аргумент
    b: list of "size" lists, each contains "size" floats --- вторая матрица-аргумент
    return c: list of "size" lists, each contains "size" floats --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц без использования функций из пакета numpy
    """
    pass

In [ ]:
def np_mult(a, b):
    """  
    a: np.array[size, size]              --- первая матрица-аргумент
    b: np.array[size, size]              --- вторая матрица-аргумент
    return c: np.array[size, size]       --- матрица, являющаяся результатом умножения матриц a и b
    
    Функция принимает на вход две матрицы: a и b размерностью size x size
    Возвращает матрицу их произведения a * b = c 

    Реализуйте умножение матриц, используя функции из пакета numpy
    """
    pass

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

In [ ]:
# проверим корректность
assert np.allclose(np.array(M1), M2)

## Задание 3
Постановка задачи линейной регрессии, о которой мы будем говорить в следующих модулях, выглядит так.

**Дано**: матрица $X$ размера $\ell \times n$ и вектор $y$ размерности $\ell$. 

**Необходимо**: подобрать вектор $w$ размерности $n$, для которого выражение $||Xw - y||^2_2$ будет минимально возможным, где $||a||_2^2$ --- квадрат нормы вектора $a$, то есть сумма квадратов компонент вектора $a$.

Даны матрица $X$ и векторы $w$, $y$. Напишите функцию, которая находит значение выражения $||Xw - y||^2_2$. Используйте библиотеку `numpy` и ее встроенные функции. Предлагаем вам загуглить, как вычислять норму вектора с помощью `numpy`. **Следите за правильными размерностями при применении линейно-алгебраических операций!**

In [39]:
def calculate_loss_function(X, w, y):
    #YOUR CODE

    return np.linalg.norm(X @ w - y)**2

In [40]:
# test
X = np.array([1,2,3,4,5,6]).reshape(3, 2)
w = np.array([0.5, -1.2])
y = np.array([2, -1, 0])

assert np.allclose(calculate_loss_function(X, w, y), 42.58999999999999)

## Задание 4
В случае, если ранг матрицы $X$ превосходит $n$, минимальное значение выражения $||Xw - y||^2_2$ при данных $X$ и $y$ достигается на векторе $$w^{*} = (X^{\top}X)^{-1}X^{\top}y.$$ 

Даны матрица $X$ размера $\ell \times n$ и вектор $y$ размера $\ell$. Вычислите значение выражения $W^{*}$ по формуле, указанной выше. Используйте встроенные матричные операции в `numpy`: матричное произведение, транспонирование, вычисление обратной матрицы. Верните на выход одномерный np.array. **Следите за правильными размерностями при применении линейно-алгебраических операций!**

In [41]:
def solve_linear_regression(X, y):
    #YOUR_CODE
    w_opt = np.linalg.inv(X.T @ X) @ X.T @ y
    
    return w_opt

In [42]:
#test
X = np.array([1,2,3,4,5,6]).reshape(3, 2)
y = np.array([2, -1, 0])

assert np.allclose(solve_linear_regression(X, y), np.array([-2.33333333,  1.83333333]))
